#!/bin/bash
# Setup Notification Methods for Orchestrator

echo "🔔 Orchestrator Notification Setup"
echo "=================================="
echo ""
echo "The Smart Orchestrator supports multiple notification methods:"
echo ""
echo "1. FILE-BASED NOTIFICATIONS (Always Active):"
echo "   - Alerts written to: /tmp/orchestration-alerts.log"
echo "   - Full logs at: /tmp/smart-orchestration.log"
echo "   - Monitor with: tail -f /tmp/orchestration-alerts.log"
echo ""
echo "2. DISCORD NOTIFICATIONS:"
echo "   Export webhook URL before starting orchestrator:"
echo "   export DISCORD_WEBHOOK='https://discord.com/api/webhooks/YOUR_WEBHOOK_URL'"
echo ""
echo "3. SLACK NOTIFICATIONS:"
echo "   Export webhook URL before starting orchestrator:"
echo "   export SLACK_WEBHOOK='https://hooks.slack.com/services/YOUR_WEBHOOK_URL'"
echo ""
echo "4. DESKTOP NOTIFICATIONS (Linux):"
echo "   Automatically enabled if notify-send is available"
echo "   Install with: sudo apt-get install libnotify-bin"
echo ""
echo "5. EMAIL NOTIFICATIONS (via cron):"
echo "   Add to crontab to check alerts every 15 minutes:"
echo "   */15 * * * * ${PROJECT_ROOT}/orchestration-framework/check-alerts.sh"
echo ""
echo "QUICK START:"
echo "============"
echo "1. Basic monitoring (file only):"
echo "   ./orchestration-framework/smart-orchestrator.sh &"
echo "   tail -f /tmp/orchestration-alerts.log"
echo ""
echo "2. With Discord notifications:"
echo "   export DISCORD_WEBHOOK='your_webhook_url'"
echo "   ./orchestration-framework/smart-orchestrator.sh &"
echo ""
echo "3. Stop the orchestrator:"
echo "   pkill -f smart-orchestrator.sh"
echo ""